version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:12.21.0
        environment:
          NEO4J_URI: bolt://localhost:7687
          NEO4J_USER: neo4j
          NEO4J_PASSWORD: 123456
          NEO4J_VERSION: 4.2.1
      - image: neo4j:enterprise
        environment:
          NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
          NEO4J_AUTH: neo4j/123456
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: npm test
workflows:
  testing:
    jobs:
      - test

